#! /bin/sh

cmd="./ldapAddUser --URI -d uid=gthuna,ou=users,cn=directoryManagement -w password -S -U"

$cmd -n "dummy, 1"
$cmd -n "dummy, 2"

exit

$cmd -n "Banks, Greg"
$cmd -n "Belcastro, Domenic"
$cmd -n "Bonnier, Guy"
$cmd -n "Coskuner, April"
$cmd -n "Dekleyn, Ron"
$cmd -n "Ditosto, Jesse"
$cmd -n "Dorchak, Darlene"
$cmd -n "Fallon, Meghann"
$cmd -n "Franco, Cristy"
$cmd -n "Franco, Tony"
$cmd -n "Freeman, Keith"
$cmd -n "Gilles, Clay"
$cmd -n "Hari, Tracey"
$cmd -n "Hribar, Johnny"
$cmd -n "Janes, Norman"
$cmd -n "Kent, Becky"
$cmd -n "Larmer, Reed"
$cmd -n "Lax, Lisa"
$cmd -n "Longbotham, Bob"
$cmd -n "Martin, Scott"
$cmd -n "Mcguire, Patrick"
$cmd -n "Mcmullen, Chris"
$cmd -n "Meinhardt, Mike"
$cmd -n "Melia, Brendon"
$cmd -n "Mercier, Shelly"
$cmd -n "Pittman, Frank"
$cmd -n "Powell, Anthony"
$cmd -n "Salmond, Becky"
$cmd -n "Samograd, Dianne"
$cmd -n "Simons, Amy"
$cmd -n "Stiles, John"
$cmd -n "Suckling, Peter"
$cmd -n "Tetz, Loralee"
$cmd -n "Thuna, Garry"
$cmd -n "Vandewalle, Donna"
$cmd -n "Wong, Robert"
