#! /usr/bin/python

import os
import ldap
import subprocess
from optparse import OptionParser
import tempfile

from ldapConf import *
from ldapUtil import *


####################################################################################
# global constants
####################################################################################
version="%prog: 2012-09-03)"
modifiedBy="Garry Thuna"


###################################################################################
# parse command line options
###################################################################################
usage = "usage: %prog [options] [uid1 [[uid2] [[...]]]" 
description = "Ensures that the user's home directory exists, "  +\
              "that it has correct user, group and acl, and "  +\
              "and sets up a subdirectory of symlinks for any workspace "  +\
              "that the user has access to"
parser = OptionParser(usage=usage, version=version, description=description)
parser.add_option("-v", "--verbose", action="store_true", dest="verbose", default=False,
                        help="show changes made to file system [default: %default]")
(options, args) = parser.parse_args()


####################################################################################
# bind to the ldap server 
#     do the preliminary procssing of users and groups
#     do the preliminary procssing of workspaces
####################################################################################
con = ldap.initialize(BIND_URI)
con.simple_bind_s(BIND_DN, BIND_PW)

groups,                \
    users,             \
     gnum2idx,         \
     gid2idx,          \
     uid2idx,          \
     belongsTo,        \
    workspaces,        \
     gtwsName2ws,      \
     gtwsName2path,    \
     gnum2gtwsName,    \
     uid2gtwsName,     \
    servers,           \
     gtsName2server  = preProcessLdapObjects(con)

con.unbind_s()


####################################################################################
# set up the homes
####################################################################################
smbConf = ''  #string in which to accumulate the samba share definitions
for u in users:
    dn, attrs = u
    uid = attrs['uid'][0]

    # is the user's home is on this server
    if 'sambaHomePath' not in attrs:
        print >> sys.stderr, '  *** Error no "sambaHomePath" set for user: ' + uid
        continue
    if attrs['sambaHomePath'][0].lower().find(SERVER_SHORT_NAME.lower()) < 0:
        continue

    # accumulate the share definition in a string
    userDir = os.path.join(SAMBA_HOME, uid)
    smbConf = smbConf + SAMBA_HOME_TEMPLATE.format(
            shareName    = uid,
            shareComment = 'home directory of ' + attrs['cn'][0],
            sharePath    = userDir
        )

    # were specific workspaces specified on the command line
    if len(args) > 0 and uid.lower() not in [a.lower() for a in args]:
        continue

    if options.verbose: 
        print 'processing user:',
        print uid \
            + '  (' + attrs['uidNumber'][0] + ')  ' \
            + 'dn: ' + dn

    # create user's directory
    userDir = os.path.join(SAMBA_HOME, uid)
    if options.verbose: 
        print '    ensuring user directory exists:       ' + userDir
    p = subprocess.Popen([ "mkdir", "-p", userDir ]); p.wait()
    if p.returncode:
        print >> sys.stderr, '  *** Error (re)creating directory: ' + userDir
    if options.verbose: 
        print '    setting ownership and permissions on: ' + userDir
    setOwnerGroupPerms(userDir, attrs['uidNumber'][0], 'anonymous', 0500)

    # create user's home/personal directory
    homeDir = os.path.join(userDir, SAMBA_USER_HOME)
    if options.verbose: 
        print '    ensuring user home directory exists:       ' + homeDir
    p = subprocess.Popen([ "mkdir", "-p", homeDir ]); p.wait()
    if p.returncode:
        print >> sys.stderr, '  *** Error (re)creating directory: ' + homeDir
    if options.verbose: 
        print '    setting ownership and permissions on: ' + homeDir
    setOwnerGroupPerms(homeDir, attrs['uidNumber'][0], 'anonymous', 02700)

    # determine the unique set of workspaces that the user can access
    accessibleWsNames= list()
    for gnum in belongsTo[ uid ]:                       #groups that user belongs to
        if gnum in gnum2gtwsName:                       #there are workspaces to which this gnum has access
            for gtwsName in gnum2gtwsName[gnum]:        #workspaces accessible by gnum
                if gtwsName not in accessibleWsNames:   #if we haven't already added workspace to list
                    accessibleWsNames.append(gtwsName)  # then do so
    if uid in uid2gtwsName:                             #there are workspaces to which this uid has access
        for gtwsName in uid2gtwsName[uid]:              #workspaces accessible by uid
            if gtwsName not in accessibleWsNames:       #if we haven't already added workspace to list
                accessibleWsNames.append(gtwsName)      # then do so

    # modify the accessbileWsNames so that we also have the server and path
    # and then sort by the server + path
    accessibles = [ (x,) + gtwsName2path[x] for x in accessibleWsNames ]
    accessibles.sort(key=lambda x: x[1]+x[2])

    # setup the linkFiles to accessible workspaces
    linkFiles = list()
    for gtwsName, gtsName, path in accessibles:
        serverAttrs = gtsName2server[gtsName][1]
        serverDir = os.path.join(userDir, serverAttrs['gtsNickname'][0])
        if not os.path.exists(serverDir):
            os.mkdir(serverDir)
        if options.verbose: 
            print '    setting ownership and permissions on: ' + serverDir
        setOwnerGroupPerms(serverDir, attrs['uidNumber'][0], attrs['gidNumber'][0], 0500)

        # write out the linkFile/URL
        wsDn, wsAttr = gtwsName2ws[gtwsName] 
        linkFile = os.path.join(serverDir, wsAttr['gtwsName'][0] + '.url')
        if options.verbose: 
            print '    writing link file: ' + linkFile
        with open(linkFile, 'w') as f:
            f.write("[InternetShortcut]" + "\r\n")
            f.write("URL=file://" + serverAttrs['gtsFQDN'][0] + "/" + wsAttr['gtwsName'][0] + "\r\n")
        setOwnerGroupPerms(linkFile, attrs['uidNumber'][0], attrs['gidNumber'][0], 0400)
        linkFiles.append(linkFile)

    # remove links no longer available
    if options.verbose: 
        print '    removing dead/revoked links'
    for dirpath, dirnames, filenames in os.walk(userDir):
        if dirpath == userDir:
            if SAMBA_USER_HOME in dirnames:
                dirnames.remove(SAMBA_USER_HOME)
            continue
        for f in filenames:
            if f.endswith('.url'):
                linkName = os.path.join(dirpath, f)  #reconstruct full linkfile path
                if linkName not in linkFiles:
                    if options.verbose: 
                        print '        removing link ' + linkName
                    os.unlink(os.path.join(dirpath, f))

    # cleanup: if subdir is empty then remove it 
    if options.verbose: 
        print '    cleanup links'
    for dirpath, dirnames, filenames in os.walk(userDir):
        if dirpath == userDir:
            if SAMBA_USER_HOME in dirnames:
                dirnames.remove(SAMBA_USER_HOME)
            continue
        if len(dirnames) + len(filenames) == 0:
            if options.verbose: 
                print '        deleting empty server folder:  ' + dirpath
            os.rmdir(dirpath)

#    # setup the static linkFiles
#    staticDir = os.path.join(userDir, 'links')
#    if not os.path.exists(staticDir):
#        os.mkdir(staticDir)
#    if options.verbose: 
#        print '    setting ownership and permissions on: ' + staticDir
#    setOwnerGroupPerms(staticDir, attrs['uidNumber'][0], attrs['gidNumber'][0], 0500)
#
#    # write out the static linkFile/URL
#    linkFile = os.path.join(staticDir, 'changePassword.url')
#    if options.verbose: 
#        print '    writing link file: ' + linkFile
#    with open(linkFile, 'w') as f:
#        f.write("[InternetShortcut]" + "\r\n")
#        f.write("URL=https://dirsrv1peg.yyc.avmaxgroup.com/changePassword.html" + "\r\n")
#    setOwnerGroupPerms(linkFile, attrs['uidNumber'][0], attrs['gidNumber'][0], 0400)

# write out the smb conf for homes
with open(os.path.join(SAMBA_ROOT, SAMBA_HOME_CONF), 'w') as f:
    f.write(smbConf)

