#! /usr/local/bin/python

import sys
import ldap
from optparse import OptionParser

from ldapConf import *
from ldapUtil import *


####################################################################################
# global constants
####################################################################################
version="%prog: 2012-09-03"
modifiedBy="Garry Thuna"


###################################################################################
# parse command line options
###################################################################################
usage = "usage: %prog [options]" 
description = "Find the maximum uidNumber and gidNumber used under " + BASE_DN
parser = OptionParser(usage=usage, version=version, description=description)
(options, args) = parser.parse_args()


####################################################################################
# bind to the ldap server
#     do the preliminary procssing of users and groups
#     do the preliminary procssing of workspaces
####################################################################################
con = ldap.initialize(BIND_URI)
#con.start_tls_s()
con.simple_bind_s(BIND_DN, BIND_PW)

groups,                \
    users,             \
     gid2group,        \
     uid2user,         \
     belongsTo,        \
    workspaces,        \
     gtwsName2ws,      \
     gtwsName2path,    \
     gid2gtwsName,     \
     uid2gtwsName,     \
    servers,           \
     gtsName2server  = preProcessLdapObjects(con)

con.unbind_s()


####################################################################################
# calc the maximums
####################################################################################
print '==============================================================='
print '= ID Numbers                                                  ='
print '==============================================================='

maxUidNumber = 0 
maxUidNumberDN = ''
for u in users:
    cur = int(u[1]['uidNumber'][0])
    if cur > maxUidNumber:
        maxUidNumber = cur
        maxUidNumberDN = u[0]

maxGidNumber = 0 
maxGidNumberDN = ''
for g in groups:
    cur = int(g[1]['gidNumber'][0])
    if cur > maxGidNumber:
        maxGidNumber = cur
        maxGidNumberDN = g[0]

print "max uidNumber: ", maxUidNumber, maxUidNumberDN
print "max gidNumber: ", maxGidNumber, maxGidNumberDN
print
print "first available uidNumber: ", firstUnusedUidNumber(users)
print "first available gidNumber: ", firstUnusedGidNumber(groups)
print
    
