#! /usr/local/bin/python

#####################################################################
# take an ldif that has been processed by ldifJoin and split long lines
# into continuation lines
#####################################################################
import sys

for line in sys.stdin:
    line = line[:-1]
    while len(line) > 78:
        print line[:78]
        line = ' ' + line[78:]
    print line

